import asyncio
import aiohttp
import time
import random
import socket
import json
from app.core.config import SERVER_URL, OUTPUT_JSONL

# ============================================================
# CONFIGURACIÓN
# ============================================================
SERVER = SERVER_URL
NUM_PREGUNTAS = 100
CONCURRENCY_LIMIT = 20

OUTPUT = OUTPUT_JSONL

# with open(OUTPUT, "w", encoding="utf-8") as f:
#     pass

PREGUNTAS = [
"¿Puede un conductor avanzar con luz verde si la intersección está congestionada?",
"¿Quién tiene prioridad en una intersección donde ambos vehículos llegan al mismo tiempo y no hay señalización?",
"¿Qué ocurre si un conductor no respeta la prioridad de paso del peatón?",
"¿Se puede adelantar en una curva si no viene ningún vehículo de frente?",
"¿Está permitido estacionar a menos de cinco metros de una esquina?",
"¿Un vehículo puede circular sin llevar la cédula de identificación si el titular está presente?",
"¿Puede un conductor usar luces altas dentro de una zona urbana sin alumbrado público?",
"¿Es obligatorio el uso del cinturón de seguridad para los pasajeros traseros?",
"¿Se puede transportar a un menor en el asiento delantero si lleva cinturón?",
"¿Qué debe hacer un conductor al aproximarse a un paso a nivel sin barreras?",
"¿Puede un ciclista circular por una autopista si no existe ciclovía alternativa?",
"¿Está permitido detenerse sobre la banquina para hablar por teléfono?",
"¿Qué debe hacer un conductor si la luz amarilla aparece justo antes de la línea de detención?",
"¿Se puede girar a la derecha con luz roja si no hay señal que lo prohíba?",
"¿Quién tiene prioridad en una rotonda: el que ingresa o el que ya circula?",
"¿Es obligatorio encender las luces bajas durante el día en rutas nacionales?",
"¿Se puede circular marcha atrás en una autopista para retomar una salida?",
"¿Qué distancia mínima debe mantenerse respecto del vehículo precedente en ruta?",
"¿Puede un vehículo circular si tiene una luz de posición quemada durante el día?",
"¿Está permitido el uso de auriculares mientras se conduce?",
"¿Qué ocurre si un conductor se niega a realizar un control de alcoholemia?",
"¿Se puede estacionar frente a una entrada de garaje si el conductor permanece dentro del vehículo?",
"¿Puede adelantarse a otro vehículo en un paso a nivel?",
"¿Qué debe hacer un conductor al escuchar una sirena de un vehículo de emergencia?",
"¿Es obligatorio llevar matafuegos en motocicletas?",
"¿Puede un peatón cruzar por cualquier lugar si no hay senda peatonal cercana?",
"¿Se puede circular con el parabrisas fisurado?",
"¿Qué sucede si un vehículo no aprueba la revisión técnica obligatoria?",
"¿Está permitido transportar personas en la caja de una camioneta?",
"¿Puede un conductor girar en U en una avenida si no hay señal que lo prohíba?",
"¿Puede un conductor adelantarse a un vehículo detenido en una senda peatonal?",
"¿Qué debe hacer un conductor si un peatón comienza a cruzar fuera de la senda?",
"¿Se puede estacionar en doble fila si es por pocos minutos?",
"¿Quién tiene prioridad en una calle angosta donde no pasan dos vehículos a la vez?",
"¿Se puede circular sin patente si el vehículo es nuevo y aún no fue colocada?",
"¿Está permitido usar balizas para circular en segunda fila?",
"¿Qué luces deben usarse durante una tormenta intensa de día?",
"¿Puede un conductor circular con un neumático visiblemente desgastado?",
"¿Es obligatorio llevar chaleco reflectante en el vehículo?",
"¿Puede una bicicleta circular de noche sin luces si la calle está iluminada?",
"¿Se puede adelantar por la derecha en una avenida con varios carriles?",
"¿Quién tiene prioridad al salir de un garaje hacia la vía pública?",
"¿Está permitido estacionar en una parada de transporte público fuera del horario del servicio?",
"¿Qué debe hacer un conductor si un semáforo no funciona?",
"¿Puede un conductor cruzar una doble línea amarilla para adelantar un vehículo lento?",
"¿Se puede conducir con yeso o inmovilización en un brazo?",
"¿Está permitido circular con vidrios polarizados oscuros?",
"¿Puede un conductor transportar carga que sobresale del vehículo sin señalizar?",
"¿Qué sucede si un conductor provoca un accidente y se retira del lugar?",
"¿Es obligatorio señalizar una detención en la ruta aun cuando sea breve?",
"¿Se puede circular sin seguro obligatorio si el vehículo no se usa habitualmente?",
"¿Puede un conductor circular con la licencia vencida si la renovación está en trámite?",
"¿Está permitido estacionar sobre la vereda parcialmente?",
"¿Qué debe hacer un conductor al aproximarse a un cruce escolar señalizado?",
"¿Se puede circular con el escape libre o modificado?",
"¿Quién es responsable si un pasajero no usa cinturón?",
"¿Está permitido usar el teléfono celular detenido en un semáforo?",
"¿Puede un conductor cruzar un semáforo en rojo para dejar paso a una ambulancia?",
"¿Se puede estacionar en contramano en una calle de un solo sentido?",
"¿Puede circular un vehículo remolcando a otro con una soga?",
"¿Qué ocurre si un conductor no señaliza un giro?",
"¿Está permitido circular con menores en brazos dentro del vehículo?",
"¿Puede un conductor avanzar sobre la senda peatonal mientras espera el semáforo?",
"¿Se puede circular sin espejos retrovisores si la visibilidad lateral es buena?",
"¿Está permitido usar luces antiniebla sin niebla?",
"¿Qué debe hacer un conductor al ver animales sueltos en la ruta?",
"¿Puede un conductor detenerse en un puente para tomar fotografías?",
"¿Se puede circular con la puerta mal cerrada si está asegurada manualmente?",
"¿Está permitido estacionar en una pendiente sin colocar el freno de mano?",
"¿Qué debe hacer un conductor al ingresar a un túnel?",
"¿Puede un conductor circular con el capot mal cerrado?",
"¿Está permitido transportar más pasajeros de los indicados por el fabricante?",
"¿Se puede circular sin luces de freno funcionando?",
"¿Qué debe hacer un conductor al encontrarse con un control de tránsito?",
"¿Puede un conductor negarse a presentar la documentación del vehículo?",
"¿Está permitido circular por la banquina para evitar un embotellamiento?",
"¿Se puede adelantar a un vehículo que gira a la izquierda por la derecha?",
"¿Puede un conductor cruzar una intersección en amarillo si puede detenerse con seguridad?",
"¿Está permitido estacionar en una ciclovía?",
"¿Qué debe hacer un conductor si pierde una rueda en marcha?",
"¿Puede circular un vehículo con carga mal sujeta si el trayecto es corto?",
"¿Está permitido conducir descalzo?",
"¿Se puede circular con luces bajas apagadas en ciudad durante el día?",
"¿Puede un conductor obstruir una bocacalle mientras espera avanzar?",
"¿Está permitido estacionar frente a un hidrante?",
"¿Qué debe hacer un conductor al aproximarse a una obra en la vía pública?",
"¿Puede un conductor circular con la licencia de otra categoría?",
"¿Está permitido transportar combustible en envases no homologados?",
"¿Se puede circular sin placa patente trasera si la delantera está colocada?",
"¿Puede un conductor continuar la marcha si ha atropellado a un animal sin verificar daños?",
"¿Qué debe hacer un conductor si otro vehículo invade parcialmente su carril en una curva?",
"¿Está permitido adelantar en una pendiente si la visibilidad es reducida?",
"¿Puede un conductor circular con una baliza portátil en lugar de las luces reglamentarias?",
"¿Se puede estacionar en una zona señalizada como carga y descarga fuera del horario indicado?",
"¿Puede un conductor circular con el seguro vencido si no tuvo siniestros?",
"¿Está permitido usar luces intermitentes para circular bajo lluvia intensa?",
"¿Qué debe hacer un conductor si el vehículo queda detenido en un paso a nivel?",
"¿Puede un conductor ingresar a una autopista en contramano para retomar una salida perdida?",
"¿Está permitido circular con la licencia deteriorada pero legible?",
"¿Se puede conducir un vehículo sin haber recibido la cédula física aún, pero con constancia digital?"
]



async def enviar_pregunta(session, sem, idx, pregunta, stats):
    async with sem:
        t_inicio = time.perf_counter()
        try:
            async with session.post(
                SERVER, 
                json={"text": pregunta}
            ) as response:
                t_fin = time.perf_counter()
                latencia = t_fin - t_inicio
                
                if response.status == 200:
                    data = await response.json()
                    res_texto = data.get("response", "")
                    decision = data.get("decision", "unknown")
                    es_dominio = decision != "out_of_domain"
                    decision = data.get("decision", "unknown")
                    registro = {
                        "nro_respuesta": idx,
                        "pregunta": pregunta,
                        "respuesta": res_texto,
                        "latencia_segundos": round(latencia, 4),
                        "clasificacion": "in_domain" if es_dominio else "out_of_domain",
                        "decision": decision
                    }

                    # with open(OUTPUT, "a", encoding="utf-8") as f:
                    #     f.write(json.dumps(registro, ensure_ascii=False) + "\n")

                    
                    stats["ok"] += 1
                    stats["latencias"].append(latencia)

                    if decision in stats["decisions"]:
                        stats["decisions"][decision] += 1
                    else:
                        stats["decisions"]["unknown"] += 1
                    
                    status_icon = "IN" if es_dominio else "OUT"
                    decision_tag = decision.upper()

                    print(f"[{idx:03d}] {status_icon} [{decision_tag}] ({latencia:.2f}s) | Pregunta: {pregunta}")
                    print(f"      Respuesta: {res_texto[:]}...")
                    print("-" * 80)
                else:
                    stats["err"] += 1
                    print(f"[{idx:03d}] Error Status {response.status} en: {pregunta}")
        
        except Exception as e:
            stats["err"] += 1
            print(f"[{idx:03d}] Error de conexión: {e}")

async def main():
    print(f"Iniciando Test de Estrés en {SERVER}")
    print(f"Simultaneidad: {CONCURRENCY_LIMIT} | Total: {NUM_PREGUNTAS}")
    print("=" * 80)
    
    connector = aiohttp.TCPConnector(family=socket.AF_INET)
    
    async with aiohttp.ClientSession(connector=connector, trust_env=False) as session:
        try:
            async with session.get(SERVER.replace("/ask", "/docs"), timeout=2): pass
        except:
            print("El servidor no parece estar activo en el puerto 8000.")
            return

        stats = {
            "ok": 0,
            "err": 0,
            "latencias": [],
            "decisions": {
                "out_of_domain": 0,
                "qa_cache": 0,
                "rag": 0,
                "unknown": 0
            }
        }
        sem = asyncio.Semaphore(CONCURRENCY_LIMIT)
        
        t_total_inicio = time.perf_counter()
        
        tasks = [
            enviar_pregunta(session, sem, i+1, PREGUNTAS[i % len(PREGUNTAS)], stats)
            for i in range(NUM_PREGUNTAS)
        ]
        
        await asyncio.gather(*tasks)
        
        t_total_fin = time.perf_counter()
        tiempo_total = t_total_fin - t_total_inicio

    # ============================================================
    # REPORTE FINAL
    # ============================================================
    if stats["latencias"]:
        avg_lat = sum(stats["latencias"]) / len(stats["latencias"])
        max_lat = max(stats["latencias"])
        min_lat = min(stats["latencias"])
    else:
        avg_lat = max_lat = min_lat = 0

    print("\n" + "=" * 80)
    print("REPORTE DE RENDIMIENTO")
    print("=" * 80)
    print(f"Peticiones exitosas:  {stats['ok']}")
    print(f"Peticiones fallidas:  {stats['err']}")
    print(f"Tiempo total test:    {tiempo_total:.2f}s")
    print(f"Throughput:           {stats['ok']/tiempo_total:.2f} req/s")
    print("DISTRIBUCIÓN DE RESPUESTAS")
    total = sum(stats["decisions"].values()) or 1

    for k, v in stats["decisions"].items():
        pct = (v / total) * 100
        print(f" - {k:14s}: {v:4d} ({pct:5.1f}%)")

    print("-" * 40)
    print(f"Latencia Promedio:    {avg_lat:.3f}s")
    print(f"Latencia Mínima:      {min_lat:.3f}s")
    print(f"Latencia Máxima:      {max_lat:.3f}s")
    print("=" * 80)

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nTest cancelado por el usuario.")














# PREGUNTAS = [
#     "¿Qué condiciones debe reunir un vehículo para poder circular legalmente por la vía pública?",
#     "¿Qué documentación es obligatoria para conducir un automotor en Argentina?",
#     "¿Qué requisitos debe cumplir la licencia de conducir para ser válida?",
#     "¿Cuándo se considera que un conductor está en condiciones psicofísicas aptas para manejar?",
#     "¿Qué obligación tiene el conductor respecto al dominio del vehículo?",
#     "¿Qué se entiende por velocidad precautoria según la ley?",
#     "¿Qué factores deben considerarse para determinar una velocidad segura?",
#     "¿Qué prioridad tiene el peatón en la vía pública?",
#     "¿Dónde deben circular los peatones en zona urbana?",
#     "¿Cuándo deben los peatones cruzar por la senda peatonal?",
#     "¿Qué prioridad tiene el vehículo que viene por la derecha en una encrucijada?",
#     "¿En qué casos no rige la prioridad de paso del vehículo que viene por la derecha?",
#     "¿Qué deben hacer los conductores al aproximarse a una bocacalle sin señalización?",
#     "¿Qué obligación tiene un conductor al acercarse a un paso a nivel ferroviario?",
#     "¿Qué vehículos tienen prioridad absoluta de paso?",
#     "¿En qué condiciones pueden circular los vehículos de emergencia?",
#     "¿Qué requisitos deben cumplir los automotores respecto a los sistemas de freno?",
#     "¿Qué características deben tener los neumáticos de un vehículo?",
#     "¿Qué dispositivos de seguridad deben tener los automotores obligatoriamente?",
#     "¿Qué tipo de vidrios deben tener los automotores para circular legalmente?",
#     "¿Qué requisitos deben cumplir los espejos retrovisores?",
#     "¿Qué sistema de iluminación debe tener un automotor?",
#     "¿Cuándo es obligatorio el uso de luces bajas?",
#     "¿Cuándo deben utilizarse las luces altas?",
#     "¿En qué situaciones deben usarse las balizas intermitentes?",
#     "¿Qué luces deben encenderse obligatoriamente al circular por rutas nacionales?",
#     "¿Qué condiciones deben cumplir las luces de giro?",
#     "¿Qué tipo de bocina está permitido utilizar en vehículos particulares?",
#     "¿Qué está prohibido respecto al uso de señales acústicas?",
#     "¿Qué condiciones deben cumplir los paragolpes de los automotores?",
#     "¿Qué dispositivos deben impedir la apertura inesperada de puertas?",
#     "¿Qué requisitos debe cumplir el sistema de escape de un vehículo?",
#     "¿Qué límites deben respetar los vehículos respecto a la emisión de contaminantes?",
#     "¿Qué obligación tiene el conductor antes de iniciar la marcha?",
#     "¿Qué distancia mínima debe mantenerse respecto al vehículo que circula adelante?",
#     "¿En qué situaciones está prohibido adelantar a otro vehículo?",
#     "¿Cómo debe realizarse correctamente una maniobra de adelantamiento?",
#     "¿Cuándo está permitido adelantar por la derecha?",
#     "¿Qué debe hacer el conductor adelantado?",
#     "¿Qué reglas deben respetarse al circular por autopistas?",
#     "¿Qué vehículos tienen prohibido circular por autopistas?",
#     "¿Qué está prohibido hacer en la banquina?",
#     "¿Qué normas rigen para la detención y estacionamiento en zona urbana?",
#     "¿Dónde está prohibido estacionar?",
#     "¿Cómo debe realizarse el estacionamiento paralelo al cordón?",
#     "¿Qué obligaciones tiene el conductor al estacionar en pendientes?",
#     "¿Qué precauciones deben tomarse al abrir la puerta de un vehículo estacionado?",
#     "¿Qué normas deben respetarse al circular en rotondas?",
#     "¿Quién tiene prioridad en una rotonda?",
#     "¿Qué obligación tiene el conductor al girar en una intersección?",
#     "¿Con cuánta anticipación debe señalizarse un giro?",
#     "¿Qué debe hacer un conductor si el semáforo cambia a luz amarilla?",
#     "¿Qué debe hacer un conductor ante una luz roja?",
#     "¿Qué significa una luz verde intermitente?",
#     "¿Qué debe hacer un conductor si, aun con luz verde, no hay espacio para avanzar?",
#     "¿Qué normas deben respetarse en cruces ferroviarios?",
#     "¿Qué condiciones deben cumplir los vehículos remolcados?",
#     "¿Qué requisitos deben cumplir los talleres de reparación de vehículos?",
#     "¿Qué obligaciones tienen los fabricantes respecto a la seguridad de los vehículos?",
#     "¿Qué es la revisión técnica obligatoria?",
#     "¿Qué aspectos evalúa la revisión técnica obligatoria?",
#     "¿Qué responsabilidades tiene el titular registral del vehículo?",
#     "¿Qué obligaciones tiene el conductor en caso de accidente?",
#     "¿Qué debe hacerse para señalizar un vehículo detenido por emergencia?",
#     "¿Qué normas deben respetarse al transportar cargas?",
#     "¿Qué condiciones deben cumplir las cargas para no afectar la seguridad vial?",
#     "¿Qué normas rigen para el transporte de menores en automóviles?",
#     "¿Dónde deben viajar los niños en un vehículo?",
#     "¿Qué elementos de seguridad deben usar los ocupantes del vehículo?",
#     "¿En qué casos es obligatorio el uso del cinturón de seguridad?",
#     "¿Qué obligaciones tiene el conductor respecto a los pasajeros?",
#     "¿Qué condiciones deben cumplir las bicicletas para circular legalmente?",
#     "¿Qué elementos de seguridad deben tener las bicicletas?",
#     "¿Dónde deben circular las bicicletas cuando existen ciclovías?",
#     "¿Qué normas deben respetar los ciclistas en la vía pública?",
#     "¿Qué obligación tienen las autoridades respecto a la infraestructura para bicicletas?",
#     "¿Qué está prohibido respecto a conducir bajo efectos de alcohol o drogas?",
#     "¿Qué conductas se consideran peligrosas para la seguridad vial?",
#     "¿Qué significa conducción negligente?",
#     "¿Qué significa conducción imprudente?",
#     "¿Qué obligación tiene el conductor respecto a las señales de tránsito?",
#     "¿Qué prioridad tienen las indicaciones de la autoridad de tránsito?",
#     "¿Qué significa señalización horizontal?",
#     "¿Qué significa señalización vertical?",
#     "¿Qué tipos de señales de tránsito existen?",
#     "¿Qué debe hacer un conductor ante una señal de PARE?",
#     "¿Qué debe hacer un conductor ante una señal de CEDA EL PASO?",
#     "¿Qué indica una doble línea amarilla continua?",
#     "¿Qué indica una línea blanca discontinua?",
#     "¿Qué significa una senda peatonal?",
#     "¿Qué condiciones deben respetarse en zonas escolares?",
#     "¿Qué normas rigen para la circulación en caminos rurales?",
#     "¿Qué precauciones deben tomarse al conducir de noche?",
#     "¿Qué debe hacer un conductor ante condiciones climáticas adversas?",
#     "¿Qué normas deben respetarse en túneles y pasos estrechos?",
#     "¿Qué responsabilidades tiene el conductor respecto al mantenimiento del vehículo?",
#     "¿Qué sanciones pueden aplicarse por infracciones graves?",
#     "¿Qué se entiende por vía pública según la ley de tránsito?",
#     "¿Qué objetivos tiene la Ley Nacional de Tránsito?",
# ]






# PREGUNTAS = [
#     "¿Qué dispositivos de seguridad deben tener los automotores según la ley para circular legalmente?",
#     "¿Es obligatorio que todos los asientos de un automóvil tengan cinturones de seguridad?",
#     "¿Qué tipo de vehículos están exceptuados de llevar paragolpes trasero?",
#     "¿Qué características deben cumplir los paragolpes de los automotores según la normativa?",
#     "¿Qué sistema de limpieza y desempañado debe tener el parabrisas de un automotor?",
#     "¿Qué requisitos debe cumplir el sistema retrovisor de un automotor?",
#     "¿Qué tipo de bocina deben llevar los automotores y qué sonoridad debe tener?",
#     "¿Qué tipo de vidrios deben tener los automotores para cumplir con la ley?",
#     "¿Qué protección deben tener los automotores contra el encandilamiento solar?",
#     "¿Qué dispositivo deben tener los automotores para cortar rápidamente la energía?",
#     "¿Qué sistema de retroceso deben tener los automotores?",
#     "¿Dónde y cómo deben estar ubicados los retrorreflectantes en los automotores?",
#     "¿Qué tipo de sistema de renovación de aire deben tener los automotores?",
#     "¿Qué sistemas deben tener los automotores para evitar la apertura inesperada de puertas, baúl y capó?",
#     "¿Qué tipo de traba de seguridad deben tener las puertas traseras de los automotores?",
#     "¿Dónde deben estar ubicados los mandos e instrumental del conductor en un automotor?",
#     "¿Qué información debe contener el tablero de instrumentos de un automotor?",
#     "¿Qué tipo de fusibles deben tener los automotores y cómo deben estar distribuidos?",
#     "¿Qué características de diseño deben tener los automotores para prevenir incendios y facilitar la evacuación?",
#     "¿Qué tipo de faros delanteros deben tener los automotores y qué colores están permitidos?",
#     "¿Qué luces de posición deben tener los automotores y de qué colores?",
#     "¿Qué características deben tener las luces de giro de los automotores?",
#     "¿Qué tipo de luces de freno deben tener los automotores y cuándo deben encenderse?",
#     "¿Qué luz debe tener la patente trasera de un automotor?",
#     "¿Qué tipo de luz de retroceso deben tener los automotores?",
#     "¿Qué luces intermitentes de emergencia deben tener los automotores?",
#     "¿Qué tipo de sistema de destello de luces frontales deben tener los automotores?",
#     "¿Qué luces deben llevar los vehículos de tracción animal según la ley?",
#     "¿Qué luces deben llevar los velocípedos para circular de noche?",
#     "¿Qué luces deben llevar las motocicletas según la normativa?",
#     "¿Qué luces deben llevar los acoplados de los vehículos?",
#     "¿Qué luces adicionales deben tener los camiones articulados o con acoplado?",
#     "¿Qué luces adicionales deben tener las grúas para remolque?",
#     "¿Qué luces adicionales deben tener los vehículos de transporte de pasajeros?",
#     "¿Qué luces adicionales deben tener los vehículos que transportan menores de 14 años?",
#     "¿Qué tipo de balizas deben llevar los vehículos policiales y de seguridad?",
#     "¿Qué tipo de balizas deben llevar los vehículos de bomberos y servicios de urgencia?",
#     "¿Qué tipo de balizas deben llevar las ambulancias?",
#     "¿Qué tipo de balizas deben llevar la maquinaria especial y los vehículos de auxilio?",
#     "¿Qué requisitos deben cumplir los automotores respecto a la emisión de contaminantes y ruidos?",
#     "¿Qué dispositivo antirrobo deben tener los automotores?",
#     "¿Qué documento debe tener todo vehículo destinado a circular por la vía pública?",
#     "¿Qué caracteres identificatorios deben tener grabados los vehículos y en qué lugares?",
#     "¿Qué es la revisión técnica obligatoria y cada cuánto debe realizarse?",
#     "¿Qué piezas y sistemas se examinan en la revisión técnica periódica de un vehículo?",
#     "¿Qué requisitos deben cumplir los talleres de reparación de vehículos?",
#     "¿Qué responsabilidad tiene el director técnico de un taller de reparación de vehículos?",
#     "¿Qué prioridad tienen las indicaciones de la autoridad de tránsito frente a las señales y normas legales?",
#     "¿Qué documentos debe presentar un conductor al ser requerido por la autoridad competente?",
#     "¿Por qué lugares deben transitar los peatones en zona urbana?",
#     "¿Cómo deben cruzar los peatones la calzada en zona urbana?",
#     "¿Por dónde deben transitar los peatones en zona rural y qué precauciones deben tomar de noche?",
#     "¿Qué deben hacer los peatones si existen cruces a distinto nivel con senda para peatones?",
#     "¿Qué debe verificar un conductor antes de ingresar a la vía pública?",
#     "¿Qué cuidados debe tener un conductor al circular por la vía pública?",
#     "¿Qué documentación debe llevar un conductor para circular con un automotor?",
#     "¿Qué requisitos debe cumplir la cédula de identificación del automotor?",
#     "¿En qué formato puede exhibirse el comprobante de seguro del vehículo?",
#     "¿Qué características deben tener las placas de identificación de dominio de un vehículo?",
#     "¿Qué requisitos adicionales deben cumplir los vehículos del servicio de transporte o maquinaria especial?",
#     "¿Qué elementos de seguridad deben llevar los automotores, excepto las motocicletas?",
#     "¿Cuántos ocupantes puede llevar un vehículo según su capacidad?",
#     "¿Dónde deben viajar los menores de 10 años en un automotor?",
#     "¿Qué sistemas de seguridad deben estar en buen estado de funcionamiento en un automotor?",
#     "¿Qué requisitos deben cumplir los ocupantes de una motocicleta para circular?",
#     "¿Qué requisitos debe cumplir una bicicleta para circular legalmente?",
#     "¿Qué sistema de rodamiento, dirección y freno debe tener una bicicleta?",
#     "¿Qué tipo de espejos retrovisores debe tener una bicicleta?",
#     "¿Qué dispositivo acústico debe llevar una bicicleta?",
#     "¿Qué tipo de casco debe usar el conductor de una bicicleta?",
#     "¿Qué tipo de ropa y calzado debe usar el conductor de una bicicleta?",
#     "¿Puede una bicicleta transportar a más de un ocupante? ¿En qué condiciones?",
#     "¿Qué tipo de guardabarros debe tener una bicicleta?",
#     "¿Qué luces y señalización reflectiva debe tener una bicicleta para circular de noche?",
#     "¿Qué debe hacer un conductor si su vehículo no cumple con los requisitos de seguridad?",
#     "¿Qué debe hacer un conductor si su vehículo no pasa la revisión técnica obligatoria?",
#     "¿Qué debe hacer un conductor si su vehículo emite contaminantes por encima de los límites permitidos?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los sistemas de seguridad originales en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las placas de identificación de dominio legibles?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene matafuego o balizas portátiles normalizados?",
#     "¿Qué debe hacer un conductor si su vehículo transporta más ocupantes de los permitidos?",
#     "¿Qué debe hacer un conductor si su vehículo no cumple con las dimensiones, peso o potencia adecuados para la vía?",
#     "¿Qué debe hacer un conductor si su motocicleta no tiene parabrisas?",
#     "¿Qué debe hacer un conductor si los ocupantes de su vehículo no usan los correajes de seguridad?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el comprobante de seguro vigente?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene la cédula de identificación?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los retrorreflectantes en los lugares reglamentarios?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el sistema de limpieza y desempañado del parabrisas en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el sistema retrovisor en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene la bocina con la sonoridad reglamentada?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los vidrios de seguridad normalizados?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene la protección contra encandilamiento solar?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el dispositivo para corte rápido de energía?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el sistema motriz de retroceso?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las luces de posición en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las luces de giro en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las luces de freno en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene la luz para la patente trasera?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene la luz de retroceso?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las luces intermitentes de emergencia?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el sistema de destello de luces frontales?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las luces adicionales que corresponden según su tipo?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el dispositivo antirrobo?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los caracteres identificatorios grabados indeleblemente?",
#     "¿Qué debe hacer un conductor si su vehículo no cumple con los límites de emisión de contaminantes?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el sistema de renovación de aire interior en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las traba de seguridad para niños en las puertas traseras?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los mandos e instrumental ubicados del lado izquierdo?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los fusibles interruptores automáticos en cantidad suficiente?",
#     "¿Qué debe hacer un conductor si su vehículo no cumple con las características de diseño para prevenir incendios?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las luces de posición delanteras y traseras en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las luces laterales en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las luces de giro intermitentes en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene la luz para la patente trasera en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene la luz de retroceso en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las luces intermitentes de emergencia en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el sistema de destello de luces frontales en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene las balizas adicionales que corresponden según su tipo?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el sistema de limpieza y lavado del parabrisas en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el sistema de desempañado del parabrisas en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los guardabarros en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los paragolpes en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los retrorreflectantes en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el sistema de mandos e instrumental con ideogramas normalizados?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene el velocímetro y cuentakilómetros en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los indicadores de luz de giro en buen estado?",
#     "¿Qué debe hacer un conductor si su vehículo no tiene los testigos de luces alta y de posición en buen estado?",
#     "¿Qué requisitos de seguridad debe cumplir una bicicleta para poder circular legalmente?",
#     "¿Es obligatorio que una bicicleta tenga espejos retrovisores? ¿Cuántos y en qué posición?",
#     "¿Qué tipo de dispositivo acústico debe llevar una bicicleta para circular?",
#     "¿Es obligatorio el uso de casco para el conductor de una bicicleta?",
#     "¿Qué tipo de ropa se recomienda usar al conducir una bicicleta según la ley?",
#     "¿Qué tipo de calzado debe usar el conductor de una bicicleta para cumplir con la normativa?",
#     "¿Puede una bicicleta transportar a más de un ocupante? ¿En qué condiciones?",
#     "¿Qué peso máximo puede transportar una bicicleta sin poner en riesgo su maniobrabilidad?",
#     "¿Es obligatorio que las bicicletas tengan guardabarros en ambas ruedas?",
#     "¿Qué tipo de luces y señalización reflectiva debe tener una bicicleta para circular de noche o en condiciones de baja visibilidad?",
#     "¿En qué situaciones se pierde la prioridad de paso del vehículo que viene por la derecha en una encrucijada?",
#     "¿Qué vehículos tienen prioridad de paso absoluta en una encrucijada, incluso sobre el que viene por la derecha?",
#     "¿Qué debe hacer un conductor al acercarse a una encrucijada con un vehículo ferroviario?",
#     "¿Qué prioridad tienen los vehículos del servicio público de urgencia en una encrucijada?",
#     "¿Qué precauciones debe tomar un conductor al ingresar o cruzar una semiautopista?",
#     "¿Qué prioridad tienen los peatones al cruzar la calzada por la senda peatonal?",
#     "¿Qué reglas especiales existen para las rotondas respecto a la prioridad de paso?",
#     "¿Qué debe hacer un conductor si desemboca desde una vía de tierra a una pavimentada?",
#     "¿Qué prioridad tiene un conductor que circula al costado de vías férreas respecto a otro que sale de un paso a nivel?",
#     "¿Qué debe hacer un conductor si se detiene o va a girar para ingresar a otra vía?",
#     "¿Qué prioridad tienen los vehículos de tracción a sangre en una encrucijada?",
#     "¿Qué debe hacer un conductor en una cuesta estrecha si lleva acoplado y otro vehículo asciende?",
#     "¿Qué pasos debe seguir un conductor para adelantar a otro vehículo de manera segura?",
#     "¿Qué debe verificar un conductor antes de iniciar un adelantamiento?",
#     "¿En qué situaciones está prohibido adelantar a otro vehículo?",
#     "¿Cómo debe advertir un conductor su intención de adelantar a otro vehículo?",
#     "¿Qué señales debe usar un conductor durante todo el proceso de adelantamiento?",
#     "¿Qué debe hacer el conductor del vehículo que está siendo adelantado?",
#     "¿Qué señal debe usar un conductor para indicar a otros que no es seguro adelantarlo?",
#     "¿Qué deben hacer los camiones y maquinaria especial para facilitar el adelantamiento en caminos angostos?",
#     "¿En qué situaciones excepcionales está permitido adelantar por la derecha?",
#     "¿Qué debe hacer un conductor antes de realizar un giro en una encrucijada?",
#     "¿Con cuánta antelación debe señalizar un conductor su intención de girar?",
#     "¿Por qué lado de la calzada debe circular un conductor que va a realizar un giro?",
#     "¿Qué velocidad debe mantener un conductor al realizar un giro?",
#     "¿Qué señales adicionales debe usar un conductor al girar para ingresar en una vía de poca importancia?",
#     "¿Cómo debe circular un conductor al ingresar, transitar y salir de una rotonda?",
#     "¿Qué prioridad tiene un vehículo que ya circula por una rotonda frente a uno que intenta ingresar?",
#     "¿Qué debe hacer un conductor al acercarse a un semáforo con luz verde?",
#     "¿Qué debe hacer un conductor al acercarse a un semáforo con luz roja?",
#     "¿Qué debe hacer un conductor al acercarse a un semáforo con luz amarilla?",
#     "¿Qué significa una luz intermitente amarilla en un semáforo y cómo debe actuar el conductor?",
#     "¿Qué significa una luz intermitente roja en un semáforo y cómo debe actuar el conductor?",
#     "¿Qué debe hacer un conductor al acercarse a un paso a nivel cuando comienza a descender la barrera?",
#     "¿Cuándo pueden cruzar los peatones una calzada regulada por semáforos?",
#     "¿Qué deben hacer los peatones si no hay semáforo peatonal pero sí vehicular?",
#     "¿Qué normas sobre prioridad de paso no rigen en las vías reguladas por semáforos?",
#     "¿Qué velocidad máxima está permitida en vías con semáforos coordinados?",
#     "¿Qué debe hacer un conductor si, al tener luz verde, no hay espacio suficiente del otro lado de la encrucijada?",
#     "¿Está permitido girar a la izquierda en vías de doble mano reguladas por semáforos?",
#     "¿En qué situaciones está permitido circular por carriles intermedios en vías multicarril?",
#     "¿Qué debe hacer un conductor al cambiar de carril en una vía multicarril?",
#     "¿Qué señal debe usar un conductor para indicar su intención de cambiar de carril?",
#     "¿Qué debe evitar un conductor para no estorbar la fluidez del tránsito en una vía multicarril?",
#     "¿Qué debe hacer un conductor si circula a menor velocidad que la de operación de su carril en una vía multicarril?",
#     "¿Qué precauciones debe tomar un conductor al circular por una vía multicarril?",
#     "¿Qué debe hacer un conductor si el vehículo que lo precede indica su intención de girar o detenerse a la izquierda?",
#     "¿Qué debe hacer un conductor si se encuentra en un embotellamiento y la fila de la izquierda no avanza?",
#     "¿Qué debe hacer un conductor al acercarse a una encrucijada sin semáforo y con otro vehículo que viene por la derecha?",
#     "¿Qué debe hacer un conductor si se encuentra con un vehículo de emergencia en una encrucijada?",
#     "¿Qué debe hacer un conductor si desemboca desde una vía de tierra a una pavimentada en una encrucijada?",
#     "¿Qué debe hacer un conductor si circula al costado de vías férreas y otro vehículo sale de un paso a nivel?",
#     "¿Qué debe hacer un conductor si se detiene o va a girar para ingresar a otra vía en una encrucijada?",
#     "¿Qué debe hacer un conductor si conduce animales o vehículos de tracción a sangre en una encrucijada?",
#     "¿Qué debe hacer un conductor si se encuentra en una cuesta estrecha y lleva acoplado?",
#     "¿Qué debe hacer un conductor si el vehículo que lo precede en una vía multicarril circula a menor velocidad que la permitida?",
#     "¿Qué debe hacer un conductor si necesita cambiar de carril en una vía multicarril?",
#     "¿Qué debe hacer un conductor si se acerca a una rotonda y hay otros vehículos circulando por ella?",
#     "¿Qué debe hacer un conductor si se acerca a una rotonda y no hay vehículos circulando por ella?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada con semáforo en rojo y hay peatones cruzando?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada con semáforo en amarillo y no está seguro de poder cruzar antes de que cambie a rojo?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada con semáforo en verde pero hay un embotellamiento del otro lado?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada con semáforo intermitente en amarillo?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada con semáforo intermitente en rojo?",
#     "¿Qué debe hacer un conductor si se acerca a un paso a nivel y la barrera comienza a descender?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada y hay un vehículo de tracción a sangre cruzando?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada y hay un vehículo de emergencia aproximándose?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada y hay un peatón cruzando por una zona peligrosa señalizada?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada y hay un vehículo que viene por la derecha pero también hay un vehículo de emergencia?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada y hay un vehículo que viene por la derecha pero también hay un vehículo ferroviario aproximándose?",
#     "¿Qué debe hacer un conductor si se acerca a una encrucijada y hay un vehículo que viene por la derecha pero también hay un vehículo que sale de una semiautopista?",
#     "¿En qué tipo de vías los vehículos de pasajeros y de carga, excepto automóviles y camionetas, deben circular únicamente por el carril derecho?",
#     "¿Qué deben hacer los vehículos de tracción a sangre si no tienen carril exclusivo y les está permitido circular?",
#     "¿Qué acción debe realizar un vehículo cuando el que lo sigue le advierte su intención de sobrepaso?",
#     "¿Para qué se utiliza el carril extremo izquierdo en las autopistas?",
#     "¿Qué tipo de vehículos no pueden circular por las autopistas?",
#     "¿Está permitido estacionar o detenerse en una autopista para subir o bajar pasajeros?",
#     "¿Qué deben hacer los vehículos remolcados por accidente o desperfecto mecánico en una autopista?",
#     "¿Qué obligación tienen las autoridades respecto a la planificación de ciclovías?",
#     "¿Qué tipo de luces deben mantener encendidas los vehículos al circular por rutas nacionales, tanto de día como de noche?",
#     "¿En qué situaciones es obligatorio el uso de luz alta en zona rural y autopistas?",
#     "¿Cuándo deben usarse las luces bajas, de posición y de chapa patente?",
#     "¿En qué momentos se debe utilizar el destello de luces según la ley?",
#     "¿Para qué situaciones están destinadas las luces intermitentes de emergencia?",
#     "¿Qué luces deben encenderse siempre conforme a sus fines propios, independientemente de la luz natural?",
#     "¿Qué dispositivos de encendido automático de luces deben incorporar los fabricantes e importadores de vehículos 0 km?",
#     "¿Qué nivel de alcoholemia está permitido al conducir cualquier tipo de vehículo?",
#     "¿Qué prohibiciones existen respecto a la conducción bajo efectos de estupefacientes o medicamentos?",
#     "¿Está permitido ceder el volante a una persona sin licencia de conducir?",
#     "¿Qué maniobras están prohibidas en la vía pública que puedan afectar la seguridad de otros conductores?",
#     "¿Pueden los menores de 18 años conducir ciclomotores en zonas céntricas o de gran concentración de vehículos?",
#     "¿Qué distancia mínima deben mantener los ómnibus y camiones entre sí al transitar por caminos?",
#     "¿En qué situaciones está permitido remolcar un vehículo que no esté destinado a ese fin?",
#     "¿Cuántos acoplados puede tener un tren de vehículos, según la ley?",
#     "¿Qué tipo de cargas no pueden transportarse en vehículos no destinados a ese fin?",
#     "¿Qué restricciones existen para transportar cargas que sobresalgan o afecten la visibilidad del conductor?",
#     "¿Está permitido realizar reparaciones en vehículos en zonas urbanas?",
#     "¿Qué normas existen sobre dejar animales sueltos o arrear hacienda en la vía pública?",
#     "¿Qué elementos en los vehículos están prohibidos si pueden ser peligrosos para otros usuarios de la vía?",
#     "¿Qué tipo de cubiertas no están permitidas en los vehículos?",
#     "¿En qué situaciones está permitido el uso de la bocina o señales acústicas?",
#     "¿Qué tipo de vehículos no pueden circular con bandas de rodamiento metálicas o elementos que dañen la calzada?",
#     "¿Qué restricciones existen para circular con vehículos que emitan contaminantes por encima de los límites permitidos?",
#     "¿Está permitido conducir utilizando auriculares o sistemas de comunicación de operación manual continua?",
#     "¿Qué elementos en la parte delantera o trasera de los vehículos están prohibidos si sobresalen de los límites de los paragolpes?",
#     "¿Cómo debe realizarse el estacionamiento en zona urbana según la ley?",
#     "¿Qué distancia mínima debe dejarse entre vehículos al estacionar en paralelo?",
#     "¿En qué lugares está prohibido estacionar en zona urbana?",
#     "¿Puede un vehículo estacionar frente a la puerta de un hospital o escuela?",
#     "¿Qué restricciones existen para estacionar frente a la salida de cines o teatros durante su funcionamiento?",
#     "¿Por cuánto tiempo máximo puede estacionarse un vehículo en la vía pública sin ser considerado infracción?",
#     "¿Qué tipo de vehículos no pueden estacionarse en cualquier lugar de la vía pública?",
#     "¿Existen espacios reservados para vehículos determinados en la vía pública?",
#     "¿Cómo debe realizarse el estacionamiento en zona rural?",
#     "¿Qué obligaciones tienen los establecimientos con gran concurrencia de público respecto al estacionamiento de bicicletas?",
#     "¿Qué se considera velocidad precautoria según la ley?",
#     "¿Qué factores debe considerar un conductor para circular a velocidad precautoria?",
#     "¿Cuáles son los límites máximos de velocidad en zona urbana para calles y avenidas?",
#     "¿Qué velocidad máxima pueden alcanzar las motocicletas y automóviles en zona rural?",
#     "¿Cuál es la velocidad máxima permitida para microbuses, ómnibus y casas rodantes motorizadas en zona rural?",
#     "¿A qué velocidad máxima pueden circular los camiones y vehículos con casa rodante acoplada en zona rural?",
#     "¿Qué velocidad máxima deben respetar los vehículos que transportan sustancias peligrosas en zona rural?",
#     "¿Qué tipo de vehículos pueden circular a la velocidad de coordinación de los semáforos en vías con semaforización coordinada?",
#     "¿Qué debe hacer un conductor si no puede mantener el dominio de su vehículo a la velocidad que circula?",
#     "¿Qué tipo de vehículos deben circular por el carril derecho en vías multicarril?",
#     "¿Qué vehículos pueden utilizar el carril izquierdo en autopistas y para qué fines?",
#     "¿Qué vehículos no pueden circular por autopistas según la ley?",
#     "¿Qué acciones están prohibidas en las autopistas respecto al ascenso y descenso de pasajeros?",
#     "¿Qué deben hacer los vehículos remolcados por accidente en una autopista?",
#     "¿Qué obligación tienen las autoridades respecto a la construcción de ciclovías?",
#     "¿Qué luces deben mantener encendidas los vehículos en rutas nacionales durante el día y la noche?",
#     "¿En qué situaciones es obligatorio el uso de luz alta?",
#     "¿Cuándo deben usarse las luces bajas, de posición y de chapa patente?",
#     "¿Para qué se utiliza el destello de luces según la ley?",
#     "¿En qué situaciones deben usarse las luces intermitentes de emergencia?",
#     "¿Qué luces deben encenderse siempre según su función, independientemente de la luz natural?",
#     "¿Qué dispositivos deben incorporar los fabricantes de vehículos 0 km respecto al encendido automático de luces?",
#     "¿Qué nivel de alcoholemia está permitido al conducir?",
#     "¿Qué prohibiciones existen respecto a la conducción bajo efectos de sustancias?",
#     "¿Está permitido ceder el volante a una persona sin licencia?",
#     "¿Qué maniobras están prohibidas en la vía pública que puedan afectar la seguridad?",
#     "¿Pueden los menores de 18 años conducir ciclomotores en zonas céntricas?",
#     "¿Qué distancia mínima deben mantener los ómnibus y camiones entre sí?",
#     "¿En qué situaciones está permitido remolcar un vehículo no destinado a ese fin?",
#     "¿Cuántos acoplados puede tener un tren de vehículos?",
#     "¿Qué tipo de cargas no pueden transportarse en vehículos no destinados a ese fin?",
#     "¿Qué restricciones existen para transportar cargas que sobresalgan o afecten la visibilidad?",
#     "¿Está permitido realizar reparaciones en vehículos en zonas urbanas?",
#     "¿Qué normas existen sobre dejar animales sueltos o arrear hacienda en la vía pública?",
#     "¿Qué elementos en los vehículos están prohibidos si pueden ser peligrosos para otros usuarios?",
#     "¿Qué tipo de cubiertas no están permitidas en los vehículos?",
#     "¿En qué situaciones está permitido el uso de la bocina o señales acústicas?",
#     "¿Qué tipo de vehículos no pueden circular con bandas de rodamiento metálicas?",
#     "¿Qué restricciones existen para circular con vehículos que emitan contaminantes por encima de los límites?",
#     "¿Está permitido conducir utilizando auriculares?",
#     "¿Qué elementos en la parte delantera o trasera de los vehículos están prohibidos si sobresalen de los límites de los paragolpes?",
#     "¿Cómo debe realizarse el estacionamiento en zona urbana?",
#     "¿Qué distancia mínima debe dejarse entre vehículos al estacionar en paralelo?",
#     "¿En qué lugares está prohibido estacionar en zona urbana?",
#     "¿Puede un vehículo estacionar frente a la puerta de un hospital o escuela?",
#     "¿Qué restricciones existen para estacionar frente a la salida de cines o teatros durante su funcionamiento?",
#     "¿Por cuánto tiempo máximo puede estacionarse un vehículo en la vía pública?",
#     "¿Qué tipo de vehículos no pueden estacionarse en cualquier lugar de la vía pública?",
#     "¿Existen espacios reservados para vehículos determinados en la vía pública?",
#     "¿Cómo debe realizarse el estacionamiento en zona rural?",
#     "¿Qué obligaciones tienen los establecimientos con gran concurrencia de público respecto al estacionamiento de bicicletas?",
#     "¿Qué se considera velocidad precautoria según la ley?",
#     "¿Qué factores debe considerar un conductor para circular a velocidad precautoria?",
#     "¿Cuáles son los límites máximos de velocidad en zona urbana?",
#     "¿Qué velocidad máxima pueden alcanzar las motocicletas y automóviles en zona rural?",
#     "¿Cuál es la velocidad máxima permitida para microbuses, ómnibus y casas rodantes motorizadas en zona rural?",
#     "¿A qué velocidad máxima pueden circular los camiones y vehículos con casa rodante acoplada en zona rural?",
#     "¿Qué velocidad máxima deben respetar los vehículos que transportan sustancias peligrosas en zona rural?",
#     "¿Qué tipo de vehículos pueden circular a la velocidad de coordinación de los semáforos en vías con semaforización coordinada?",
#     "¿Qué debe hacer un conductor si no puede mantener el dominio de su vehículo a la velocidad que circula?"
# ]















# PREGUNTAS = [
#     "¿Por qué en calles con varios carriles no todos los vehículos pueden circular por cualquier carril?",
#     "¿Qué tipo de vehículos deben usar únicamente el carril derecho en avenidas con varios carriles?",
#     "¿Cuándo está permitido usar el carril izquierdo en una vía con muchos carriles?",


#     "¿Qué debe hacer un conductor si otro vehículo le avisa que quiere adelantarlo?",


#     "¿Cómo deben circular los vehículos tirados por animales cuando no hay un carril exclusivo?",
#     "¿Qué diferencia hay entre una autopista y una vía común con varios carriles?",
#     "¿Para qué se reserva el carril izquierdo en una autopista?",



#     "¿Qué tipos de vehículos tienen prohibido circular por autopistas?",



#     "¿Está permitido detenerse en una autopista para subir o bajar pasajeros?",
#     "¿En qué lugares de una autopista se permite detenerse por emergencias?",


#     "¿Qué deben hacer los vehículos remolcados cuando circulan por una autopista?",



#     "¿Las mismas reglas de las autopistas se aplican a las semiautopistas?",
#     "¿Por qué se promueve la construcción de ciclovías en las ciudades?",
#     "¿Es obligatorio usar la ciclovía cuando existe una disponible?",
#     "¿Quiénes están obligados a circular por ciclovías o sendas especiales?",
#      "¿Está permitido usar las luces rompenieblas en cualquier momento?",



#     "¿Cuándo es obligatorio encender las luces del vehículo aunque sea de día?",
#     "¿En qué situaciones se deben usar las luces bajas o las luces diurnas?",
#     "¿Cuándo corresponde utilizar la luz alta del vehículo?",
#     "¿En qué casos deben encenderse las luces de posición y de la patente?",
#     "¿Para qué situaciones se usa el destello de luces?",
#     "¿Cuándo se deben utilizar las luces intermitentes de emergencia?",   
#     "¿Para qué fines específicos deben usarse las luces adicionales del vehículo?",
#     "¿Deben encenderse las luces de freno o giro aunque haya buena iluminación natural?",
#     "¿Por qué los vehículos nuevos deben tener un sistema automático de luces?",
#     "¿Qué tipo de sustancias o medicamentos impiden conducir legalmente?",
#     "¿Está permitido manejar después de consumir alcohol en cualquier cantidad?",
#     "¿Qué consecuencias puede tener conducir sin estar en condiciones físicas o mentales adecuadas?",
#     "¿Es legal prestar el vehículo a alguien que no tiene habilitación para conducir?",
#     "¿Por qué está prohibido circular en contramano?",
#     "¿Cuándo se puede circular por la banquina?",
#     "¿Por qué es peligroso reducir la velocidad de manera brusca sin motivo?",
#     "¿Qué maniobras se consideran imprudentes o peligrosas al conducir?",
#     "¿Los menores pueden conducir ciclomotores en zonas de mucho tránsito?",
#     "¿Qué se considera una obstrucción indebida en una bocacalle?",
#     "¿Por qué es importante mantener una distancia prudente con el vehículo de adelante?",
#     "¿En qué casos está permitido circular marcha atrás?",
#     "¿Cuándo se considera irregular la detención de un vehículo?",
#     "¿Está permitido estacionar sobre la banquina si no hay una emergencia?",
#     "¿Por qué no se debe cambiar de carril en curvas o encrucijadas?",
#     "¿Qué riesgos implica adelantarse en zonas peligrosas?",
#     "¿Por qué no se debe detener un vehículo cerca de un cruce ferroviario?",
#     "¿Qué condiciones deben tener las cubiertas para circular legalmente?",
#     "¿Por qué las motos y bicicletas no deben circular sujetas a otros vehículos?",
#     "¿Qué distancia deben mantener entre sí los camiones en rutas comunes?",
#     "¿En qué casos está permitido remolcar otro vehículo?",
#     "¿Cuántos acoplados puede llevar un vehículo de forma legal?",
#     "¿Por qué hay restricciones para transportar cargas a granel?",
#     "¿Qué tipo de cargas pueden afectar la visibilidad del conductor?",
#     "¿Está permitido reparar un vehículo en plena calle?",
#     "¿En qué casos se permite arrear animales por caminos públicos?",
#     "¿Por qué está prohibido vender productos en la calzada o banquina?",
#     "¿Qué elementos en las ruedas pueden dañar la calzada?",
#     "¿Está permitido usar bocina libremente en la ciudad?",
#     "¿Qué tipo de ruidos o emisiones están prohibidos en los vehículos?",
#     "¿Se puede conducir usando auriculares o dispositivos de comunicación manuales?",
#     "¿Por qué algunos accesorios externos del vehículo pueden ser peligrosos?",
#     "¿Cómo debe realizarse el estacionamiento en calles urbanas?",
#     "¿Qué distancia mínima debe dejarse entre vehículos estacionados?",
#     "¿En qué lugares está prohibido estacionar por razones de seguridad?",
#     "¿Por qué no se permite estacionar cerca de esquinas o cruces?",
#     "¿Está permitido detenerse sobre sendas peatonales?",
#     "¿Qué restricciones existen frente a hospitales y escuelas?",
#     "¿Por qué no se puede estacionar frente a garages en uso?",
#     "¿Cuánto tiempo máximo se puede dejar un vehículo estacionado en la vía pública?",
#     "¿Qué tipos de vehículos tienen mayores restricciones para estacionar en la ciudad?",
#     "¿Pueden existir espacios reservados para ciertos vehículos?",
#     "¿Cómo se debe estacionar en zonas rurales?",
#     "¿Por qué es obligatorio prever espacios para bicicletas en lugares concurridos?",
#     "¿Qué se entiende por velocidad precautoria al conducir?",
#     "¿De qué factores depende la velocidad segura de circulación?",
#     "¿Qué debe hacer un conductor si pierde el control del vehículo?",
#     "¿Cuáles son los límites de velocidad en calles urbanas comunes?",
#     "¿Cuál es la velocidad permitida en avenidas?",
#     "¿Por qué algunas vías urbanas tienen velocidades coordinadas con semáforos?",
#     "¿Cuál es la velocidad máxima permitida para autos en rutas?",
#     "¿Por qué los camiones tienen límites de velocidad más bajos?",
#     "¿Qué precauciones especiales deben tomar los transportes de sustancias peligrosas?",
# ]





# PREGUNTAS = [
#     "¿Está permitido adelantar en una curva?",
#     "¿Cuál es la velocidad máxima en zona urbana?",
#     "¿Cómo preparo una tortilla de papas?", 
#     "¿Qué sanción aplica por alcoholemia positiva?",
#     "¿Se puede estacionar frente a un garaje?",
#     "¿Cómo programar en Rust?", 
#     "¿Es obligatorio el uso de casco en motos?",
#     "¿Cuál es la capital de Francia?", 
#     "¿Cuál es la velocidad máxima en zona urbana?",
#     "¿Está permitido adelantar en una curva?",
#     "¿Es obligatorio el uso de casco en motos?",
#     "¿Qué sanción aplica por alcoholemia positiva?",
#     "¿Cuándo es obligatorio encender las luces bajas del vehículo?",
#     "¿Qué documentos se deben portar al conducir un automóvil?",
#     "¿Está permitido estacionar sobre la vereda?",
#     "¿Cuál es la edad mínima para obtener la licencia de conducir en Argentina?",
#     "¿Qué velocidad máxima permite la Ley de Tránsito en rutas nacionales?",
#     "¿Qué consecuencias tiene no respetar un semáforo en rojo?",
#     "¿Cómo programar en Rust?",
#     "¿Cuál es la capital de Francia?",
#     "¿Cómo preparo una tortilla de papas?",
#     "¿Quién ganó el Mundial de Fútbol 2018?",
#     "¿Qué es la teoría de la relatividad?",
#     "¿Cómo funciona un motor de combustión interna?",
#     "¿Cuál es la receta para hacer pan casero?",
#     "¿Cuándo fue inventada la imprenta?",
#     "¿Qué animales viven en la selva amazónica?",
#     "¿Cómo aprender a tocar guitarra desde cero?",
#     ]


# PREGUNTAS = [
#     "¿Cuál es la edad mínima para obtener la licencia de conducir un automóvil particular en Argentina?",
#     "¿Qué documentos son necesarios para tramitar la licencia de conducir por primera vez?",
#     "¿Cuántas clases teóricas y prácticas son obligatorias para obtener la licencia de conducir?",
#     "¿Qué tipo de examen médico se debe realizar para sacar la licencia de conducir?",
#     "¿Cuál es la validez de la licencia de conducir para menores de 21 años?",
#     "¿Cuál es la validez de la licencia de conducir para mayores de 21 años?",
#     "¿Qué se considera infracción grave según la ley de tránsito?",
#     "¿Cuál es la sanción por conducir sin licencia de conducir?",
#     "¿Está permitido adelantar en una curva?",
#     "¿Cuál es la velocidad máxima en zona urbana?",
#     "¿Cómo preparo una tortilla de papas?", 
#     "¿Qué sanción aplica por alcoholemia positiva?",
#     "¿Se puede estacionar frente a un garaje?",
#     "¿Cómo programar en Rust?", 
#     "¿Es obligatorio el uso de casco en motos?",
#     "¿Cuál es la capital de Francia?", 
#     "¿Cuál es la velocidad máxima en zona urbana?",
#     "¿Está permitido adelantar en una curva?",
#     "¿Es obligatorio el uso de casco en motos?",
#     "¿Qué sanción aplica por alcoholemia positiva?",
#     "¿Cuándo es obligatorio encender las luces bajas del vehículo?",
#     "¿Qué documentos se deben portar al conducir un automóvil?",
#     "¿Está permitido estacionar sobre la vereda?",
#     "¿Cuál es la edad mínima para obtener la licencia de conducir en Argentina?",
#     "¿Qué velocidad máxima permite la Ley de Tránsito en rutas nacionales?",
#     "¿Qué consecuencias tiene no respetar un semáforo en rojo?",
#     "¿Cómo programar en Rust?",
#     "¿Cuál es la capital de Francia?",
#     "¿Cómo preparo una tortilla de papas?",
#     "¿Quién ganó el Mundial de Fútbol 2018?",
#     "¿Qué es la teoría de la relatividad?",
#     "¿Cómo funciona un motor de combustión interna?",
#     "¿Cuál es la receta para hacer pan casero?",
#     "¿Cuándo fue inventada la imprenta?",
#     "¿Qué animales viven en la selva amazónica?",
#     "¿Cómo aprender a tocar guitarra desde cero?",
#     "¿Qué se debe hacer si se pierde la licencia de conducir?",
#     "¿Cuál es el límite de alcohol en sangre permitido para conductores de automóviles particulares?",
#     "¿Qué sanción corresponde si se conduce con una alcoholemia superior al límite permitido?",
#     "¿Cuál es la velocidad máxima permitida en zonas urbanas?",
#     "¿Cuál es la velocidad máxima permitida en autopistas?",
#     "¿Qué documentos deben portarse obligatoriamente al conducir un vehículo?",
#     "¿Qué se debe hacer si se es testigo de un accidente de tránsito?",
#     "¿Cuál es la sanción por no respetar un semáforo en rojo?",
#     "¿Qué se considera conducción temeraria y cuál es su sanción?",
#     "¿Cuál es la sanción por exceso de velocidad?",
#     "¿Qué se debe hacer si se sufre un accidente de tránsito?",
#     "¿Cuál es la sanción por no usar el cinturón de seguridad?",
#     "¿Cuál es la sanción por no usar casco en motocicletas?",
#     "¿Qué se debe hacer si se quiere transportar carga en un vehículo particular?",
#     "¿Cuál es la sanción por conducir un vehículo sin seguro obligatorio?",
#     "¿Qué se debe hacer si se quiere transportar menores de edad en un vehículo?",
#     "¿Cuál es la sanción por no respetar la prioridad de paso?",
#     "¿Qué se debe hacer si se quiere realizar un giro en U en una avenida?",
#     "¿Cuál es la sanción por estacionar en lugares prohibidos?",
#     "¿Qué se debe hacer si se quiere adelantar a otro vehículo?",
#     "¿Cuál es la sanción por usar el celular mientras se conduce?",
#     "¿Qué se debe hacer si se quiere transportar mascotas en un vehículo?",
#     "¿Cuál es la sanción por no respetar las señales de tránsito?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con remolque?",
#     "¿Cuál es la sanción por conducir bajo los efectos de estupefacientes?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con vidrios polarizados?",
#     "¿Cuál es la sanción por no llevar las luces encendidas cuando es obligatorio?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con matrícula extranjera?",
#     "¿Cuál es la sanción por no respetar el paso peatonal?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con luces rotas?",
#     "¿Cuál es la sanción por no llevar el extintor de incendios en el vehículo?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con neumáticos en mal estado?",
#     "¿Cuál es la sanción por no llevar la documentación del vehículo al día?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el escape roto?",
#     "¿Cuál es la sanción por no respetar la distancia de seguridad entre vehículos?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con las luces mal reguladas?",
#     "¿Cuál es la sanción por no llevar el matafuego en condiciones?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el parabrisas roto?",
#     "¿Cuál es la sanción por no respetar las indicaciones de un agente de tránsito?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con las puertas que no cierran bien?",
#     "¿Cuál es la sanción por no llevar el botiquín de primeros auxilios en el vehículo?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de frenos defectuoso?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con las luces antiniebla encendidas en la ciudad?",
#     "¿Cuál es la sanción por no respetar la señal de 'Pare'?",
#     "¿Qué se debe hacer si se quiere transportar objetos que sobresalgan del vehículo?",
#     "¿Cuál es la sanción por no llevar el chaleco reflectante en el vehículo?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con las luces de posición apagadas de noche?",
#     "¿Cuál es la sanción por no respetar la señal de 'Ceda el Paso'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con las luces altas en zona urbana?",
#     "¿Cuál es la sanción por no llevar el triángulo de seguridad en el vehículo?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con las luces intermitentes en mal funcionamiento?",
#     "¿Cuál es la sanción por no respetar la señalización horizontal en la calzada?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el limpiaparabrisas roto?",
#     "¿Cuál es la sanción por no llevar el manual del vehículo?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el espejo retrovisor roto?",
#     "¿Cuál es la sanción por no respetar la señal de 'No Estacionar'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el claxon en mal estado?",
#     "¿Cuál es la sanción por no llevar el certificado de revisión técnica vehicular?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el aire acondicionado en mal funcionamiento?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido Girar'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de dirección defectuoso?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago del seguro?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de iluminación defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Altura Máxima'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de escape en mal estado?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago del impuesto vehicular?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de suspensión defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Peso Máximo'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de refrigeración en mal estado?",
#     "¿Cuál es la sanción por no llevar el comprobante de propiedad del vehículo?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de frenos de mano defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Ancho Máximo'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de calefacción en mal estado?",
#     "¿Cuál es la sanción por no llevar el comprobante de transferencia del vehículo?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de aireación defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Largo Máximo'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de dirección asistida defectuosa?",
#     "¿Cuál es la sanción por no llevar el comprobante de verificación de emisiones contaminantes?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de encendido defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido Adelantar'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de escape de gases defectuoso?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de multas?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de iluminación interior defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Zona de Estacionamiento Regulado'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de audio en mal funcionamiento?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de patente?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de navegación defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido Retroceder'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de climatización en mal estado?",
#     "¿Cuál es la sanción por no llevar el comprobante de seguro de responsabilidad civil?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de cierre centralizado defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido Circular'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de alarma en mal funcionamiento?",
#     "¿Cuál es la sanción por no llevar el comprobante de revisión técnica vehicular al día?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de suspensión neumática defectuosa?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido Estacionar y Detenerse'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de dirección hidráulica defectuoso?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de infracciones?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de frenos antibloqueo (ABS) defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Uso de Bocina'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de control de tracción defectuoso?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de peajes?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de airbag defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Paso'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de cinturones de seguridad defectuoso?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de estacionamiento medido?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de luces de emergencia defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Días Impares'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de limpiaparabrisas trasero defectuoso?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de infracciones de tránsito?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de espejos laterales defectuosos?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Días Pares'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de luces de niebla traseras defectuosas?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de multas de tránsito?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de luces de marcha atrás defectuoso?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Horario Nocturno'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de luces de giro defectuosas?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de infracciones viales?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de luces de freno defectuosas?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Horario Diurno'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de luces de posición delanteras defectuosas?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de multas viales?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de luces de posición traseras defectuosas?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Fines de Semana'?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de luces de emergencia traseras defectuosas?",
#     "¿Cuál es la sanción por no llevar el comprobante de pago de infracciones de estacionamiento?",
#     "¿Qué se debe hacer si se quiere conducir un vehículo con el sistema de luces de niebla delanteras defectuosas?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Días Festivos'?",
# ]


# PREGUNTAS = [
#     "¿Cómo se prepara un asado argentino tradicional?",
#     "¿Cuál es la receta para hacer empanadas salteñas?",
#     "¿Cómo se cultiva la quinoa en el norte de Argentina?",
#     "¿Cuál es la historia del tango en Buenos Aires?",
#     "¿Qué sanción aplica si un conductor se niega a someterse a un control de alcoholemia?",
#     "¿Cuál es la normativa sobre el uso de luces de emergencia en vehículos detenidos en la banquina?",
#     "¿Qué requisitos debe cumplir un vehículo para ser considerado 'de uso oficial' y estar exento de ciertas restricciones?",
#     "¿Cuál es la sanción por circular con las placas de patente adulteradas o falsificadas?",
#     "¿Qué normas rigen el uso de vehículos en zonas de playas o dunas?",
#     "¿Cuál es el procedimiento para recuperar una licencia de conducir retenida por alcoholemia?",
#     "¿Qué sanción aplica por no respetar la distancia de seguridad en túneles o puentes?",
#     "¿Cuál es la normativa sobre el uso de vehículos en zonas de reserva natural o parques nacionales?",
#     "¿Cómo se elabora el vino malbec en Mendoza?",
#     "¿Cuáles son los mejores destinos turísticos en la Patagonia?",
#     "¿Cómo se prepara un locro tradicional?",
#     "¿Cuál es la historia del mate en Argentina?",
#     "¿Cómo se fabrica el dulce de leche?",
#     "¿Cuáles son las tradiciones del carnaval en el norte de Argentina?",
#     "¿Cómo afecta la ley de tránsito a los vehículos eléctricos en Argentina?",
#     "¿Qué diferencias hay entre las normas de tránsito en Argentina y en Chile?",
#     "¿Cómo se regula el uso de vehículos en zonas de frontera con países limítrofes?",
#     "¿Qué recomendaciones da la ley para conducir en zonas con alta presencia de fauna silvestre?",
#     "¿Cómo se determina la responsabilidad civil en un accidente de tránsito con daños materiales?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta altitud, como la Puna?",
#     "¿Cómo se regula el uso de vehículos en zonas de alta temperatura, como el norte argentino?",
#     "¿Qué diferencias hay entre las normas de tránsito en provincias con autonomía vial y las nacionales?",
#     "¿Cómo se regula el uso de vehículos en zonas de alta humedad o lluvias torrenciales?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta salinidad, como la región de Cuyo?",
#     "¿Cómo se prepara un guiso de lentejas?",
#     "¿Cuál es la historia del fútbol en Argentina?",
#     "¿Cuál es la receta tradicional del chimichurri argentino?",
#     "¿Cómo se prepara un buen mate cocido?",
#     "¿Cuáles son los mejores lugares para practicar buceo en Argentina?",
#     "¿Cómo se elabora el vino torrontés en Cafayate?",
#     "¿Cuál es la historia del fileteado porteño?",
#     "¿Cómo se prepara un buen asado de tira?",
#     "¿Cuáles son los mejores destinos para avistar aves en el norte argentino?",
#     "¿Cómo se prepara una sopa paraguaya?",
#     "¿Cuál es la historia del carnaval en Corrientes?",
#     "¿Cómo se cultiva el tabaco en el norte argentino?",
#     "¿Cuáles son los mejores lugares para practicar rafting en Argentina?",
#     "¿Cómo se prepara un buen guiso de mondongo?",
#     "¿Cuál es la historia del chamamé en la provincia de Corrientes?",
#     "¿Cómo se elabora el queso de cabra en la provincia de La Rioja?",
#     "¿Cuáles son los mejores lugares para practicar parapente en Argentina?",
#     "¿Cómo se prepara un buen locro criollo?",
#     "¿Cuál es la historia del folclore en Santiago del Estero?",
#     "¿Cómo se cultiva la vid en San Rafael, Mendoza?",
#     "¿Cuáles son los mejores lugares para practicar esquí de fondo en Argentina?",
#     "¿Cómo se prepara un buen pastel de papa con carne?",
#     "¿Cuál es la historia del rock en Rosario?",
#     "¿Cómo se elabora el vino malbec en Luján de Cuyo?",
#     "¿Cuáles son los mejores lugares para practicar trekking en la Patagonia?",
#     "¿Cómo se prepara un buen tamal jujeño?",
#     "¿Cuál es la historia del tango en La Boca?",
#     "¿Cómo se cultiva el olivo en Catamarca?",
#     "¿Cuáles son los mejores lugares para practicar kayak en Argentina?",
#     "¿Cómo se prepara un buen pan casero de campo?",
#     "¿Cuál es la historia del carnaval en Humahuaca?",
#     "¿Cómo se elabora el queso de cabra en la Quebrada de Humahuaca?",
#     "¿Cuáles son los mejores lugares para practicar mountain bike en Argentina?",
#     "¿Cómo se prepara un buen guiso de arvejas?",
#     "¿Cuál es la historia del folclore en Tucumán?",
#     "¿Qué requisitos debe cumplir un conductor para obtener una licencia de conducir para vehículos de transporte de carga?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Salud'?",
#     "¿Qué normas rigen el uso de luces de emergencia en vehículos de transporte público?",
#     "¿Cuál es el procedimiento para renovar la licencia de conducir si el titular reside en el extranjero?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago del impuesto a la propiedad automotor?",
#     "¿Cuál es la normativa sobre el uso de vehículos en zonas de alta contaminación sonora?",
#     "¿Qué requisitos debe cumplir un vehículo para ser considerado apto para el transporte de sustancias inflamables?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Seguridad'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta densidad de tráfico, como centros urbanos?",
#     "¿Cuál es el procedimiento para regularizar una multa por no llevar el triángulo de seguridad en el vehículo?",
#     "¿Qué requisitos debe cumplir un conductor para transportar pasajeros en vehículos de alquiler sin chofer?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos Educativos'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta pendiente o caminos de montaña?",
#     "¿Cuál es la normativa sobre el uso de luces de posición en vehículos detenidos en la vía pública?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago del seguro obligatorio en un control policial?",
#     "¿Cuál es el procedimiento para apelar una multa por exceso de velocidad en una ruta nacional?",
#     "¿Qué requisitos debe cumplir un vehículo para ser utilizado en servicios de emergencia médica?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Bomberos'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad turística, como Bariloche o Mendoza?",
#     "¿Cuál es la normativa sobre el uso de luces antiniebla en condiciones de visibilidad reducida?",
#     "¿Qué sanción aplica por no llevar el comprobante de verificación de emisiones contaminantes?",
#     "¿Cuál es el procedimiento para obtener una licencia de conducir para vehículos de transporte de pasajeros?",
#     "¿Qué requisitos debe cumplir un conductor para transportar mercancías peligrosas en vehículos particulares?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Salud'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad agrícola, como la Pampa Húmeda?",
#     "¿Cuál es la normativa sobre el uso de luces de emergencia en vehículos detenidos en autopistas?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de la patente municipal?",
#     "¿Cuál es el procedimiento para regularizar una multa por no llevar el matafuego en condiciones?",
#     "¿Qué requisitos debe cumplir un conductor para obtener una licencia de conducir para vehículos de emergencia?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Seguridad'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad ganadera, como el norte argentino?",
#     "¿Cuál es la normativa sobre el uso de luces de posición en vehículos estacionados en zonas urbanas?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de infracciones de tránsito?",
#     "¿Cuál es el procedimiento para obtener una licencia de conducir para vehículos de transporte escolar?",
#     "¿Qué requisitos debe cumplir un conductor para transportar pasajeros en vehículos de alquiler con chofer?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Bomberos'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad minera, como Catamarca o Jujuy?",
#     "¿Cuál es la normativa sobre el uso de luces de emergencia en vehículos de transporte de carga?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de peajes en un control policial?",
#     "¿Cuál es el procedimiento para renovar la licencia de conducir si el titular tiene una discapacidad?",
#     "¿Qué requisitos debe cumplir un conductor para transportar sustancias químicas en vehículos particulares?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Salud'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad forestal, como Misiones?",
#     "¿Cuál es la normativa sobre el uso de luces de posición en vehículos detenidos en zonas rurales?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de multas de tránsito?",
#     "¿Cuál es el procedimiento para obtener una licencia de conducir para vehículos de transporte de mercancías peligrosas?",
#     "¿Qué requisitos debe cumplir un conductor para transportar pasajeros en vehículos de turismo?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Seguridad'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad pesquera, como la costa patagónica?",
#     "¿Cuál es la normativa sobre el uso de luces de emergencia en vehículos de transporte público de pasajeros?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago del impuesto a la propiedad vehicular?",
#     "¿Cuál es el procedimiento para apelar una multa por no respetar un semáforo en rojo?",
#     "¿Qué requisitos debe cumplir un conductor para obtener una licencia de conducir para vehículos de transporte de carga pesada?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Salud'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad turística, como la Patagonia?",
#     "¿Cuál es la normativa sobre el uso de luces de posición en vehículos detenidos en zonas de alta montaña?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de la VTV?",
#     "¿Cuál es el procedimiento para obtener una licencia de conducir para vehículos de transporte de pasajeros en rutas internacionales?",
#     "¿Qué requisitos debe cumplir un conductor para transportar mercancías peligrosas en vehículos de carga?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Bomberos'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad agrícola, como la región pampeana?",
#     "¿Cuál es la normativa sobre el uso de luces de emergencia en vehículos de transporte escolar?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de infracciones viales?",
#     "¿Cuál es el procedimiento para renovar la licencia de conducir si el titular tiene una enfermedad crónica?",
#     "¿Qué requisitos debe cumplir un conductor para transportar pasajeros en vehículos de alquiler con chofer en zonas turísticas?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Salud'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad minera, como San Juan?",
#     "¿Cuál es la normativa sobre el uso de luces de posición en vehículos detenidos en zonas de niebla?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de multas de estacionamiento?",
#     "¿Cuál es el procedimiento para obtener una licencia de conducir para vehículos de transporte de mercancías peligrosas en rutas nacionales?",
#     "¿Qué requisitos debe cumplir un conductor para transportar pasajeros en vehículos de turismo internacional?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Seguridad'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad forestal, como el norte de Misiones?",
#     "¿Cuál es la normativa sobre el uso de luces de emergencia en vehículos de transporte de carga en autopistas?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de la patente municipal en un control policial?",
#     "¿Cuál es el procedimiento para apelar una multa por no llevar el extintor de incendios?",
#     "¿Qué requisitos debe cumplir un conductor para obtener una licencia de conducir para vehículos de transporte de pasajeros en zonas urbanas?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Bomberos'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad ganadera, como la provincia de Buenos Aires?",
#     "¿Cuál es la normativa sobre el uso de luces de posición en vehículos detenidos en zonas de alta contaminación?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de infracciones de tránsito en un control policial?",
#     "¿Cuál es el procedimiento para obtener una licencia de conducir para vehículos de transporte de mercancías peligrosas en rutas provinciales?",
#     "¿Qué requisitos debe cumplir un conductor para transportar pasajeros en vehículos de alquiler con chofer en zonas rurales?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Salud'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad turística, como la costa atlántica?",
#     "¿Cuál es la normativa sobre el uso de luces de emergencia en vehículos de transporte público en zonas urbanas?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de la VTV en un control policial?",
#     "¿Cuál es el procedimiento para renovar la licencia de conducir si el titular reside temporalmente en el exterior?",
#     "¿Qué requisitos debe cumplir un conductor para transportar mercancías peligrosas en vehículos de carga internacional?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Seguridad'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad agrícola, como el norte de Santa Fe?",
#     "¿Cuál es la normativa sobre el uso de luces de posición en vehículos detenidos en zonas de alta temperatura?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de multas de tránsito en un control policial?",
#     "¿Cuál es el procedimiento para obtener una licencia de conducir para vehículos de transporte de pasajeros en rutas nacionales?",
#     "¿Qué requisitos debe cumplir un conductor para transportar pasajeros en vehículos de alquiler con chofer en zonas urbanas?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Salud'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad minera, como la provincia de Catamarca?",
#     "¿Cuál es la normativa sobre el uso de luces de emergencia en vehículos de transporte escolar en zonas rurales?",
#     "¿Qué sanción aplica por no llevar el comprobante de pago de la patente municipal en un control vial?",
#     "¿Cuál es el procedimiento para regularizar una multa por no llevar el triángulo de seguridad en el vehículo?",
#     "¿Cómo se cultiva el limón en Tucumán?",
#     "¿Cuáles son los mejores lugares para practicar pesca deportiva en Argentina?",
#     "¿Cómo se prepara un buen asado de costillas?",
#     "¿Cuál es la historia del carnaval en Gualeguay?",
#     "¿Cómo se elabora el vino cabernet sauvignon en Maipú?",
#     "¿Cuáles son los mejores lugares para practicar senderismo en la provincia de Córdoba?",
#     "¿Cómo se prepara un buen pastel de zapallo?",
#     "¿Cuál es la historia del chamamé en Misiones?",
#     "¿Cómo se cultiva el té en Misiones?",
#     "¿Cuáles son los mejores lugares para practicar avistamiento de ballenas en Península Valdés?",
#     "¿Cómo se prepara un buen guiso de lentejas con chorizo?",
#     "¿Cuál es la historia del folclore en Salta?",
#     "¿Cómo se elabora el alfajor de maicena?",
#     "¿Cuáles son las mejores rutas para hacer trekking en la cordillera de los Andes?",
#     "¿Cómo se prepara un milanesa a la napolitana?",
#     "¿Cuál es la historia de la inmigración italiana en Argentina?",
#     "¿Cómo se cultiva la yerba mate en Misiones?",
#     "¿Cuáles son los parques nacionales más visitados en Argentina?",
#     "¿Cómo se prepara un pastel de papa?",
#     "¿Cuál es la normativa sobre el uso de vehículos en zonas de obras viales o desvíos temporales?",
#     "¿Qué requisitos debe cumplir un conductor para obtener una licencia de conducir para vehículos de emergencia?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Escuelas en Horario Escolar'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de niebla densa o condiciones meteorológicas extremas?",
#     "¿Cuál es la normativa sobre el uso de vehículos en zonas de alta contaminación ambiental?",
#     "¿Qué sanción aplica por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Comisaría'?",
#     "¿Cuál es el procedimiento para apelar una retención vehicular por falta de documentación?",
#     "¿Qué requisitos debe cumplir un vehículo para ser utilizado en competencias deportivas en vía pública?",
#     "¿Cuál es la normativa sobre el uso de vehículos en zonas de alta densidad de ciclistas?",
#     "¿Qué sanción aplica por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos Educativos'?",
#     "¿Cuál es la normativa sobre el uso de vehículos en zonas de alta congestión vehicular?",
#     "¿Qué requisitos debe cumplir un conductor para transportar pasajeros en vehículos de alquiler con chofer?",
#     "¿Cómo se regula el uso de vehículos en zonas de alta actividad sísmica?",
#     "¿Qué diferencias hay entre las normas de tránsito en zonas urbanas y rurales según la ley?",
#     "¿Cómo se regula el uso de vehículos en zonas de alta actividad turística, como Bariloche o Mendoza?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad agrícola, como la Pampa Húmeda?",
#     "¿Cómo se regula el uso de vehículos en zonas de alta actividad minera?",
#     "¿Qué diferencias hay entre las normas de tránsito para vehículos particulares y vehículos de carga?",
#     "¿Cómo se regula el uso de vehículos en zonas de alta actividad ganadera?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta actividad pesquera, como la costa patagónica?",
#     "¿Cómo se regula el uso de vehículos en zonas de alta actividad forestal?",
#     "¿Qué diferencias hay entre las normas de tránsito para vehículos de uso privado y vehículos de uso público?",
#     "¿Cuál es la sanción por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Seguridad'?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta concentración de peatones, como centros comerciales?",
#     "¿Cuál es la normativa sobre el uso de vehículos en zonas de alta pendiente o caminos sinuosos?",
#     "¿Qué sanción aplica por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Bombero'?",
#     "¿Cuál es el procedimiento para regularizar una multa por no llevar el extintor de incendios?",
#     "¿Qué requisitos debe cumplir un vehículo para ser utilizado en servicios de transporte público de pasajeros?",
#     "¿Cuál es la historia del rock nacional argentino?",
#     "¿Cómo se elabora el queso de cabra en el noroeste argentino?",
#     "¿Cuáles son las fiestas populares más importantes en Argentina?",
#     "¿Qué requisitos debe cumplir un conductor para transportar mercancías peligrosas?",
#     "¿Cuál es la sanción por no llevar el certificado de revisión técnica vehicular (VTV) en un control policial?",
#     "¿Qué normas rigen el uso de vehículos en zonas de alta montaña o caminos de cornisa?",
#     "¿Cuál es la normativa sobre el uso de luces de posición durante el día en condiciones de poca visibilidad?",
#     "¿Qué sanción aplica por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Establecimientos de Salud'?",
#     "¿Cuál es el procedimiento para regularizar una multa por exceso de velocidad?",
#     "¿Qué requisitos debe cumplir un vehículo para ser utilizado como ambulancia o vehículo de emergencia?",
#     "¿Cuál es la normativa sobre el uso de vehículos en zonas de inundación o emergencia climática?",
#     "¿Qué sanción aplica por no respetar la señal de 'Prohibido el Estacionamiento en Zonas de Acceso a Bombero'?",
#     "¿Cómo se prepara un sandwich de miga?",
#     "¿Cuál es la historia del cine argentino?",
#     "¿Cómo se cultiva el olivo en La Rioja?",
#     "¿Cuáles son los mejores lugares para practicar esquí en Argentina?",
#     "¿Cómo se prepara una torta frita?",
#     "¿Cuál es la historia del folclore argentino?",
#     "¿Cómo se elabora el vino torrontés en Salta?",
#     "¿Cuáles son los platos típicos de la cocina norteña argentina?",
#     "¿Cómo se prepara un tamal?",
#     "¿Cuál es la historia del carnaval de Gualeguaychú?",
#     "¿Cómo se cultiva el ajo en Mendoza?",
#     "¿Cuáles son los mejores lugares para avistar ballenas en Argentina?",
#     "¿Cómo se prepara una humita en chala?",
#     "¿Cuál es la historia del teatro en Argentina?",
#     "¿Cómo se elabora el queso tybo en la puna?",
#     "¿Cuáles son las rutas del vino más famosas en Argentina?",
#     "¿Cómo se prepara un curanto?",
#     "¿Cuál es la historia de la literatura gauchesca en Argentina?"
# ]